export { default as Switch } from "./Switch.vue";
export { default as Button } from "./Button.vue";
export { default as Tabs } from "./Tabs.vue";
export { default as Tab } from "./Tab.vue";
export { default as Dialog } from "./Dialog.vue";
export { default as Tag } from "./Tag.vue";
export { default as Progress } from "./Progress.vue";
export { default as CheckBox } from "./Checkbox.vue";
export { openDialog as openDialog } from "./openDialog";
